name: flutter_pos
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^5.0.0
  cached_network_image: ^2.3.2+1
  flutter_offline: ^2.0.0
  intl: ^0.17.0
  global_configuration: ^2.0.0-nullsafety.1
  device_info: ^2.0.0
  url_launcher: ^6.0.10
  auto_size_text: ^2.1.0
  http: ^0.13.1
  flutter_svg: ^0.22.0
  carousel_slider: ^3.0.0
  flutter_rating_bar: ^4.0.0
  dropdown_search: ^1.0.0
  autocomplete_textfield: ^1.7.3
  expandable: ^5.0.1
  shared_preferences: ^2.0.5
  flutter_phoenix: ^0.1.0
  status_change: ^2.0.0
  responsive_grid: ^2.0.0
  plugin_platform_interface: ^2.0.0
  share: ^2.0.4
  jiffy: ^4.1.0
  sentry_flutter: ^5.1.0
  sentry: ^5.1.0
  file_picker: ^3.0.3
  device_preview: ^0.7.3
  onesignal_flutter: ^3.2.3
  responsive_grid_list: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/i18n/
    - assets/cfg/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf



